# Numpy Problems set -1
<hr>

In [2]:
import numpy as np

In [53]:
x = [1,2]
y = [3,4]

u = [[1,2],
     [3,4]]
v = [[5,1],
     [6,2]]

##### Write a NumPy program to compute the multiplication of two given matrixes. 

In [5]:
mult = np.array(x)*np.array(y)
mult

array([3, 8])

In [7]:
np.array(u)*np.array(v)

array([[ 5,  2],
       [18,  8]])

##### Write a NumPy program to compute the outer product of two given vectors. 

In [8]:
np.outer(x,y)

array([[3, 4],
       [6, 8]])

In [9]:
np.outer(u,v)

array([[ 5,  1,  6,  2],
       [10,  2, 12,  4],
       [15,  3, 18,  6],
       [20,  4, 24,  8]])

##### Write a NumPy program to compute the cross product of two given vectors. 

In [10]:
np.cross(x,y)

array(-2)

In [11]:
np.cross(u,v)

array([ -9, -18])

##### Write a NumPy program to compute the determinant of a given square array.

In [25]:
from numpy import linalg 

In [18]:
np.linalg.det(u)

-2.0000000000000004

##### Write a NumPy program to evaluate Einstein's summation convention of two given multidimensional arrays.

In [7]:
np.einsum('i,i',x,y)                                               # inner product or dot product

11

In [12]:
np.einsum('i,i->i',x,y)                                        # Element wise multipication of 1D  --> x*y

array([3, 8])

In [13]:
np.einsum('i,i->',x,y)                                         # inner product or dot product

11

In [11]:
np.einsum('i,j->ij',x,y)                                        # outer product of 1D

array([[3, 4],
       [6, 8]])

In [10]:
np.einsum('ij,jk',u,v)                                              # np.matmul(u,v)

array([[17,  5],
       [39, 11]])

In [22]:
np.einsum('ij,kl->',u,v) 

140

In [11]:
np.einsum('ij,kl->ijkl',u,v)                                          # multiplication result in 4D array

array([[[[ 5,  1],
         [ 6,  2]],

        [[10,  2],
         [12,  4]]],


       [[[15,  3],
         [18,  6]],

        [[20,  4],
         [24,  8]]]])

In [15]:
np.einsum('ii->i',u)              # Diagonal 

array([1, 4])

In [16]:
np.einsum('ij,ij->ij',u,v)                                      # u * v

array([[ 5,  2],
       [18,  8]])

In [17]:
np.einsum('ij,ij->ij',u,u)                                      # sqaure of u

array([[ 1,  4],
       [ 9, 16]])

In [18]:
np.einsum('ii->',u)                                  # trace or sum of diagonal

5

In [19]:
np.einsum('ij->ji',u)                                           # transpose

array([[1, 3],
       [2, 4]])

In [9]:
 np.einsum('ij,ji->ij',u,v)                                                  # u * transpose of v

array([[ 5, 12],
       [ 3,  8]])

In [15]:
np.einsum('ij,kl->ik',u,v)                                        # matrix multiplication or np.matmul(arr1,arr2)

array([[18, 24],
       [42, 56]])

In [17]:
np.einsum('ij->j',u)                                               # sum along axis 0 (vertical)

array([4, 6])

In [18]:
np.einsum('ij->i',u)                                                 # sum along axis 1 (horizontal)

array([3, 7])

##### Write a NumPy program to compute the inner product of vectors for 1-D arrays (without complex conjugation) and in higher dimension

In [23]:
np.inner(x,y)

11

In [24]:
np.inner(u,v)

array([[ 7, 10],
       [19, 26]])

##### Write a NumPy program to compute the eigenvalues and right eigenvectors of a given square array.

In [29]:
val, vec = np.linalg.eig(u)
print(val)
print(vec)

[-0.37228132  5.37228132]
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


##### Write a NumPy program to compute the Kronecker product of two given mulitdimension arrays.

In [30]:
np.kron(x,y)

array([3, 4, 6, 8])

In [31]:
np.kron(u,v)

array([[ 5,  1, 10,  2],
       [ 6,  2, 12,  4],
       [15,  3, 20,  4],
       [18,  6, 24,  8]])

##### Write a NumPy program to compute the condition number of a given matrix.

In [36]:
np.linalg.cond(u)

14.933034373659268

##### Write a NumPy program to find a matrix or vector norm.

In [37]:
np.linalg.norm(u)

5.477225575051661

##### Write a NumPy program to compute the determinant of an array

In [40]:
z = [[0,1],[2,3],[4,5]]
np.linalg.det(v)

3.999999999999999

##### Write a NumPy program to compute the inverse of a given matrix

In [41]:
np.linalg.inv(u)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

##### Write a NumPy program to calculate the QR decomposition of a given matrix.

In [42]:
np.linalg.qr(u)

(array([[-0.31622777, -0.9486833 ],
        [-0.9486833 ,  0.31622777]]), array([[-3.16227766, -4.42718872],
        [ 0.        , -0.63245553]]))

##### Write a NumPy program to compute the sum of the diagonal element of a given array.

In [45]:
np.trace(u)

5

In [46]:
np.trace(v)

7

###### Write a NumPy program to compute the diagonal elements of a given array

In [47]:
np.diag(u)

array([1, 4])

##### Write a NumPy program to compute the matrix multiplication of a given array.


In [51]:
np.matmul(u,v)

array([[17,  5],
       [39, 11]])

<hr>

In [52]:
p = [[1,0],
    [0,1]]
q = [[1,2],
     [3,4]]
np.dot(p,q)                   # dot

array([[1, 2],
       [3, 4]])